apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: echo-messages-api
  description: The Echo Messages API II
spec:
  type: openapi
  lifecycle: production
  owner: group:default/thio-org
  system: thio-system
  provideApis: component:default/quarkus-cicd
  definition:
    $text: http://example-apicurioregistry-kafkasql.apicurio-registry-operator.router-default.apps.west.jgmpn.gcp.redhatworkshops.io/apis/registry/v2/groups/rhdh-dev/artifacts/openapi







    #$text: https://petstore.swagger.io/v2/swagger.json
    #http://example-apicurioregistry-kafkasql.apicurio-registry-operator.router-default.apps.west.jgmpn.gcp.redhatworkshops.io/apis/registry/v2/groups/rhdh-dev/artifacts/openapi
